### ISSUE TITLE
Provide libgtk-x11-2.0

### ISSUE THREAD

**Issue by asocaciu** [cloudfoundry/cflinuxfs3#11]
libgtk-x11-2.0 is available in cflinuxfs2 but not in cflinuxfs3. Would it be possible to add it, as we can't run our open_cv based application on cflinuxfs3 because of this missing shared library.

**Comment by tylerphelan** [comment]
@asocaciu we typically try not to add any new packages once the package list is set for the rootfs since it can have very wide-spread effects in cf. `libgtk` was intentionally removed to reduce the rootfs footprint and it only enables a subset of apps. you could try the [apt buildpack](https://github.com/cloudfoundry/apt-buildpack)
