### ISSUE TITLE
Python-dev

### ISSUE THREAD

**Issue by Gustafioh** [cloudfoundry/cflinuxfs3#13]
We had support for python-dev in cf2, but not in cf3......that's causing problems with i.e. mysqlclient. Could you please include Python-dev again?

**Comment by dfreilich** [comment]
@Gustafioh There was support for python-dev in cf2? [This issue](https://github.com/cloudfoundry/cflinuxfs2/pull/34) on cflinuxfs2 seems to imply that there wasn't support for python-dev, because it could be added through conda. 

Closing for now, because it seems like should work. If it doesn't work for your needs, feel free to reopen with a sample app, and we'll see whether we can replicate the issue and decide to add it in. Thanks!
