### ISSUE TITLE
libmagick++ and libudunits2

### ISSUE THREAD

**Issue by hedberg503** [cloudfoundry/cflinuxfs3#14]
I have a Shiny application which requires the following libraries be included in the buildpack.
   Configuration failed because Magick++ was not found. Try installing:
    - deb: 'libmagick++-dev' (Debian, Ubuntu)
    - rpm: 'ImageMagick-c++-devel' (Fedora, CentOS, RHEL)
    - csw: 'imagemagick_dev' (Solaris)
   Configuration failed because libudunits2.so was not found. Try installing:
       * deb: libudunits2-dev (Debian, Ubuntu, ...)
       * rpm: udunits2-devel (Fedora, EPEL, ...)
       * brew: udunits (OSX)

Is there a way to manually add libraries to the buildpack?

**Comment by dfreilich** [comment]
@hedberg503 Thanks for commenting, and our apologies that it took so long to respond! You can use the apt-buildpack (https://github.com/cloudfoundry/apt-buildpack) to add deb packages prior to another buildpack, so that should be of help – closing this for now. 

If that doesn't solve your problem, reopen the issue and we'll look into it!
